### PR TITLE
SEO Minor Improvements: Sitemap, canonical links

### PR DESCRIPTION
**Pull request by melissamcewen**
Hi, I noticed the sitemap wasn't being served. I think this should fix it by changing the location to the site directory.

I also noticed that the rel="canonical" was the old URLs. I think changing this env variable in build.yml should fix that but I'm not entirely sure.

### CODE REVIEW

**Review by Chriscbr — APPROVED** [review]

**Comment by Chriscbr** [comment]
Thanks @melissamcewen!

**Comment by revitalbarletz** [comment]
@melissamcewen congrats on your first PR! How about joining our slack? https://t.winglang.io/slack

**Comment by melissamcewen** [comment]
@Chriscbr looks like this worked in preview but the sitemap and canonical still have the docs.winglang.io instead of https://www.winglang.io/docs/. It might be a setting in Vercel? https://www.winglang.io/docs/sitemap.xml

**Comment by ShaiBer** [comment]
> @Chriscbr looks like this worked in preview but the sitemap and canonical still have the docs.winglang.io instead of https://www.winglang.io/docs/. It might be a setting in Vercel? https://www.winglang.io/docs/sitemap.xml

@melissamcewen it could be. I can give you access to Vercel. Which email should I give the access to?

**Pull request merged**
